env:
  browser: true
  es2021: true
  node: true
  jest: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
overrides: []
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - "@typescript-eslint"
rules:
  "@typescript-eslint/no-var-requires": 0
  "@typescript-eslint/no-require-imports": 0
  "react/prop-types": 0
settings:
  react:
    version: "detect"
